# Error when starting docker-compose up solved with https://superuser.com/questions/1401705/docker-gcloud-how-to-fix-docker-credential-gcloud-not-installed-or-not-avail
version: '3.7'

services:
  file-explorer-api:
    container_name: file-explorer-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
        - DB_HOST=postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
    name: nest-db